### ISSUE TITLE
support for authorized_keys options?

### ISSUE THREAD

**Issue by nstephens** [artem-sidorenko/puppet-sshkeys#6]
Firstly, thank you for a plugin that does exactly what I needed, and the fantastic documentation that got me going quickly!  But, I do have a question... is there support in this module for additional authorized_keys options such as "from" or "command"?

**Comment by artem-sidorenko** [comment]
Not a problem, I'm happy to see that this module is usefull for somebody else besides me:)

To your question, no, right now there is no support implemented, but as ssh_authorized_key type [implements exactly this options](http://docs.puppetlabs.com/references/latest/type.html#ssh_authorized_key-attribute-options), it should be very easy to extend this module to enable passing of options to ssh_authorized_keys.

I do not really have much time to do that, but I'm open for review and merge requests

Please close the issue if it answers your question
